<a href="https://colab.research.google.com/github/ajith18thayil/My-WorkS/blob/main/ANN_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('/content/breast_cancer.csv')

In [3]:
dataset.head(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   
6  ...          27.66           153.20      1606.0            0.1442   
7  ...          28.14           110.60       897.0            0.1654   
8  ...          30.73           106.20       739.3            0.1703   
9  ...          40.68            97.65       711.4            0.1853   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   
6             0.2576           0.3784                0.1932          0.3063   
7             0.3682           0.2678                0.1556          0.3196   
8             0.5401           0.5390                0.2060          0.4378   
9             1.0580           1.1050                0.2210          0.4366   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  
6                  0.08368          NaN  
7                  0.11510          NaN  
8                  0.10720          NaN  
9                  0.20750          NaN  

[10 rows x 33 columns]

In [4]:
dataset.tail(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
559  925291         B        11.51         23.93           74.52      403.5   
560  925292         B        14.05         27.15           91.38      600.4   
561  925311         B        11.20         29.37           70.67      386.0   
562  925622         M        15.22         30.62          103.40      716.9   
563  926125         M        20.92         25.09          143.00     1347.0   
564  926424         M        21.56         22.39          142.00     1479.0   
565  926682         M        20.13         28.25          131.20     1261.0   
566  926954         M        16.60         28.08          108.30      858.1   
567  927241         M        20.60         29.33          140.10     1265.0   
568   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
559          0.09261           0.10210         0.11120              0.04105   
560          0.09929           0.11260         0.04462              0.04304   
561          0.07449           0.03558         0.00000              0.00000   
562          0.10480           0.20870         0.25500              0.09429   
563          0.10990           0.22360         0.31740              0.14740   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
559  ...          37.16            82.28       474.2           0.12980   
560  ...          33.17           100.20       706.7           0.12410   
561  ...          38.30            75.19       439.6           0.09267   
562  ...          42.79           128.70       915.0           0.14170   
563  ...          29.41           179.10      1819.0           0.14070   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
559            0.25170           0.3630               0.09653          0.2112   
560            0.22640           0.1326               0.10480          0.2250   
561            0.05494           0.0000               0.00000          0.1566   
562            0.79170           1.1700               0.23560          0.4089   
563            0.41860           0.6599               0.25420          0.2929   
564            0.21130           0.4107               0.22160          0.2060   
565            0.19220           0.3215               0.16280          0.2572   
566            0.30940           0.3403               0.14180          0.2218   
567            0.86810           0.9387               0.26500          0.4087   
568            0.06444           0.0000               0.00000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
559                  0.08732          NaN  
560                  0.08321          NaN  
561                  0.05905          NaN  
562                  0.14090          NaN  
563                  0.09873          NaN  
564                  0.07115          NaN  
565                  0.06637          NaN  
566                  0.07820          NaN  
567                  0.12400          NaN  
568                  0.07039          NaN  

[10 rows x 33 columns]

In [5]:
dataset.shape

(569, 33)

In [6]:
X = dataset.iloc[:,2:32].values
y = dataset.iloc[:,1].values

In [7]:
X.shape

(569, 30)

In [8]:
y.shape

(569,)

In [9]:
from sklearn.preprocessing import LabelEncoder

labelEncoder=LabelEncoder()

In [10]:
y =labelEncoder.fit_transform(y)

In [11]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1,random_state = 42)


In [13]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [14]:
##ANN

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense


In [16]:
#initialising ANN
classifier = Sequential()

In [17]:

# units = (x+1)/2
#       = (30+1)/2
#       = 16


In [18]:
#creating input layer and first hidden layer
classifier.add(Dense(units = 16,kernel_initializer='uniform',activation = 'sigmoid',input_dim = 30))

#second hidden layer
classifier.add(Dense(units = 16,kernel_initializer='uniform',activation = 'sigmoid'))


#output layer
classifier.add(Dense(units = 1,kernel_initializer='uniform',activation = 'relu'))

In [19]:
classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics =['accuracy'])

In [20]:
classifier.fit(X_train,y_train,batch_size = 10,epochs = 100)

Epoch 1/100
52/52 [==============================] - 5s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 2/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 3/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 4/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 5/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 6/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 7/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 8/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 9/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 10/100
52/52 [==============================] - 0s 3ms/step - loss: 5.8747 - accuracy: 0.6191
Epoch 11/

In [21]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5)

2/2 [==============================] - 0s 3ms/step


In [22]:
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [23]:
from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_test,y_pred)

In [24]:
cm

array([[40,  0],
       [17,  0]])