<a href="https://colab.research.google.com/github/ajith18thayil/My-WorkS/blob/main/Classification_AllAlg_CancerData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#read file
df = pd.read_csv('/content/cancer_data.csv')
df.head()

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   diagnosis  
0          0  
1          0  
2          0  
3          0  
4          0

In [ ]:
df.shape

(569, 6)

In [ ]:
df.describe()

mean_radius  mean_texture  mean_perimeter    mean_area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean_smoothness   diagnosis  
count       569.000000  569.000000  
mean          0.096360    0.627417  
std           0.014064    0.483918  
min           0.052630    0.000000  
25%           0.086370    0.000000  
50%           0.095870    1.000000  
75%           0.105300    1.000000  
max           0.163400    1.000000

In [ ]:
print(df.isna().sum())

mean_radius        0
mean_texture       0
mean_perimeter     0
mean_area          0
mean_smoothness    0
diagnosis          0
dtype: int64


In [ ]:
x=df.iloc[:,:-1].values
x

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, 8.581e+02, 8.455e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, 1.265e+03, 1.178e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02]])

In [ ]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
#converting data to training data and testing data
from sklearn.model_selection import train_test_split
#splitting 70% of the data to training data and 30% of data to testing data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=1)

In [ ]:
#normalizing input data (x_train and x_test)
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_train

array([[0.21482323, 0.17653027, 0.207864  , 0.11147402, 0.43937889],
       [0.28723555, 0.32465336, 0.26826066, 0.16275716, 0.25250519],
       [0.34166312, 0.3659114 , 0.33598231, 0.20144221, 0.33113659],
       ...,
       [0.48364807, 0.50084545, 0.48655933, 0.33336161, 0.49173964],
       [0.3336173 , 0.3902604 , 0.31787713, 0.19507953, 0.34368511],
       [0.28628899, 0.29455529, 0.26826066, 0.16131495, 0.335831  ]])

In [ ]:
x_test = scaler.transform(x_test)
x_test

array([[0.36485399, 0.14440311, 0.37613157, 0.21743372, 0.45562878],
       [0.29291495, 0.30267163, 0.29154861, 0.16589608, 0.57028076],
       [0.28250272, 0.21339195, 0.27192316, 0.15703075, 0.43215672],
       [0.5361825 , 0.29996618, 0.51696496, 0.38069989, 0.30017153],
       [0.38567845, 0.67974298, 0.36569691, 0.24432662, 0.27597725],
       [0.43442662, 0.40006764, 0.43127635, 0.2826299 , 0.43486504],
       [0.57783142, 0.21068651, 0.57017483, 0.42990456, 0.3097409 ],
       [0.52529699, 0.41021305, 0.50867252, 0.37348887, 0.19030423],
       [0.16560178, 0.3432533 , 0.15845484, 0.0823754 , 0.49083687],
       [0.35728146, 0.14440311, 0.34600235, 0.212386  , 0.51701724],
       [0.19210564, 0.24078458, 0.18747841, 0.09743372, 0.49715627],
       [0.34118983, 0.47683463, 0.33916108, 0.19817603, 0.37916403],
       [0.43821288, 0.30639161, 0.44924331, 0.28063627, 0.48722578],
       [0.25457901, 0.29861346, 0.24338332, 0.13709438, 0.29015076],
       [0.36722041, 0.5312817 , 0.

In [ ]:
#naive bayes model alg
from sklearn.naive_bayes import GaussianNB
model_naive=GaussianNB()
model_naive.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_naive=model_naive.predict(x_test)
y_naive

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
matrix_naive=confusion_matrix(y_test,y_naive)
print(matrix_naive,'\n')
accuracy_naive=accuracy_score(y_test,y_naive)
print(accuracy_naive,'\n')
report_naive=classification_report(y_test,y_naive)
print(report_naive)

[[ 50  13]
 [  5 103]] 

0.8947368421052632 

              precision    recall  f1-score   support

           0       0.91      0.79      0.85        63
           1       0.89      0.95      0.92       108

    accuracy                           0.89       171
   macro avg       0.90      0.87      0.88       171
weighted avg       0.90      0.89      0.89       171



In [ ]:
#KNN model alg
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=5)
model_KNN.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_KNN=model_naive.predict(x_test)
y_KNN

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
matrix_KNN=confusion_matrix(y_test,y_KNN)
print(matrix_KNN,'\n')
accuracy_KNN=accuracy_score(y_test,y_KNN)
print(accuracy_KNN,'\n')
report_KNN=classification_report(y_test,y_KNN)
print(report_KNN)

[[ 50  13]
 [  5 103]] 

0.8947368421052632 

              precision    recall  f1-score   support

           0       0.91      0.79      0.85        63
           1       0.89      0.95      0.92       108

    accuracy                           0.89       171
   macro avg       0.90      0.87      0.88       171
weighted avg       0.90      0.89      0.89       171



In [ ]:
#SVM model alg
from sklearn.svm import SVC
model_SVC=SVC()
model_SVC.fit(x_train,y_train)

SVC()

In [ ]:
y_SVC=model_SVC.predict(x_test)
y_SVC

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
matrix_SVC=confusion_matrix(y_test,y_SVC)
print(matrix_SVC,'\n')
accuracy_SVC=accuracy_score(y_test,y_SVC)
print(accuracy_SVC,'\n')
report_SVC=classification_report(y_test,y_SVC)
print(report_SVC)

[[ 54   9]
 [  6 102]] 

0.9122807017543859 

              precision    recall  f1-score   support

           0       0.90      0.86      0.88        63
           1       0.92      0.94      0.93       108

    accuracy                           0.91       171
   macro avg       0.91      0.90      0.90       171
weighted avg       0.91      0.91      0.91       171



In [ ]:
#Decision Tree model alg
from sklearn.tree import DecisionTreeClassifier
model_dec=DecisionTreeClassifier(criterion='entropy')
model_dec.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
y_dec=model_dec.predict(x_test)
y_dec

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
matrix_dec=confusion_matrix(y_test,y_dec)
print(matrix_dec,'\n')
accuracy_dec=accuracy_score(y_test,y_dec)
print(accuracy_dec,'\n')
report_dec=classification_report(y_test,y_dec)
print(report_dec)

[[ 48  15]
 [  8 100]] 

0.8654970760233918 

              precision    recall  f1-score   support

           0       0.86      0.76      0.81        63
           1       0.87      0.93      0.90       108

    accuracy                           0.87       171
   macro avg       0.86      0.84      0.85       171
weighted avg       0.86      0.87      0.86       171



In [ ]:
print('KNN accuracy: ','\t','\t','\t',accuracy_KNN,'\n')
print('Naive Bayes accuracy: ','\t','\t',accuracy_naive,'\n')
print('SVC accuracy: ','\t','\t','\t',accuracy_SVC,'\n')
print('Decision Tree accuracy: ','\t',accuracy_dec,'\n')

KNN accuracy:  	 	 	 0.8947368421052632 

Naive Bayes accuracy:  	 	 0.8947368421052632 

SVC accuracy:  	 	 	 0.9122807017543859 

Decision Tree accuracy:  	 0.8654970760233918 

